name: Project â€” Close Issue
on:
  issues:
    types:
      - closed
      - opened
jobs:
  handle-close:
    name: Match issue to GitHub project
    runs-on: ubuntu-24.04
    if: github.event.action == 'closed'
    steps:
      - uses: actions/add-to-project@v1.0.2
        id: add
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          project-url: https://github.com/orgs/spear-ai/projects/41
      - name: Set the status based on the close reason
        id: status
        run: |
          case "${{ github.event.issue.state_reason }}" in
            "completed")
              echo "status=Done" >> $GITHUB_OUTPUT
              ;;
            "duplicate")
              echo "status=Duplicate" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "status=Canceled" >> $GITHUB_OUTPUT
              ;;
          esac
      - uses: kalgurn/update-project-item-status@v0.0.3
        with:
          project-url: https://github.com/orgs/spear-ai/projects/41
          github-token: ${{ secrets.GH_TOKEN }}
          item-id: ${{ steps.add.outputs.itemId }}
          status: ${{ steps.status.outputs.status }}
  handle-open:
    name: Match issue to GitHub project
    runs-on: ubuntu-24.04
    if: github.event.action == 'opened'
    steps:
      - uses: actions/add-to-project@v1.0.2
        id: add
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          project-url: https://github.com/orgs/spear-ai/projects/41
      - uses: kalgurn/update-project-item-status@v0.0.3
        with:
          project-url: https://github.com/orgs/spear-ai/projects/41
          github-token: ${{ secrets.GH_TOKEN }}
          item-id: ${{ steps.add.outputs.itemId }}
          status: Backlog
