name: Project
on:
  issues:
    types:
      - assigned
      - closed
      - labeled
      - opened
      - reopened
      - unassigned
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - ready_for_review
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
jobs:
  automatically_setup_pull_request:
    if: github.event_name == 'issues'
    runs-on: ubuntu-24.04
    steps:
      - name: Automatically create a draft pull request when an issue is marked as `Todo`
        uses: robvanderleek/create-issue-branch@v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          autoDeleteBranch: true
          autoLinkIssue: true
          commentMessage: "Branch ${branchName} created for issue: ${issue.title}"
          copyIssueAssigneeToPR: true
          copyIssueDescriptionToPR: true
          copyIssueLabelsToPR: true
          copyIssueMilestoneToPR: true
          copyIssueProjectsToPR: true
          openDraftPR: true
          prSkipCI: true
  handle-issue-closed:
    if: github.event_name == 'issues' && github.event.action == 'closed'
    runs-on: ubuntu-24.04
    steps:
      - id: status
        name: Set the status based on the close reason
        run: |
          case "${{ github.event.issue.state_reason }}" in
            "completed")
              echo "status=Done" >> $GITHUB_OUTPUT
              ;;
            "duplicate")
              echo "status=Duplicate" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "status=Canceled" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Update project
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          field-name: Status
          field-value: ${{ steps.status.outputs.status }}
          github-token: ${{ secrets.GH_TOKEN }}
          project-url: https://github.com/orgs/spear-ai/projects/41
  handle-issue-opened:
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      issues: write
    steps:
      - name: Update project
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          field-name: Status
          field-value: Backlog
          github-token: ${{ secrets.GH_TOKEN }}
          project-url: https://github.com/orgs/spear-ai/projects/41
      - id: parsed-issue
        name: Parse issue
        uses: stefanbuck/github-issue-parser@v3.2.1
        with:
          template-path: .github/ISSUE_TEMPLATE/feature.yml
      - name: Set labels based on severity field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3.2.2
        with:
          issue-form: ${{ steps.parsed-issue.outputs.jsonString }}
          token: ${{ secrets.GH_TOKEN }}
  handle-pull-request:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-24.04
    permissions:
      issues: read
      pull-requests: write
    steps:
      - name: Require a pull request to have at least one linked issue
        uses: nearform-actions/github-action-check-linked-issues@v1.8.3
        with:
          exclude-branches: "dependabot/**, deploy"
  handle-review:
    if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
    runs-on: ubuntu-24.04
    steps:
      - name: Update project
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          field-name: Status
          field-value: In review
          github-token: ${{ secrets.GH_TOKEN }}
          project-url: https://github.com/orgs/spear-ai/projects/41
permissions:
  contents: read
